[package]
name = "todo_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] } # "serde" feature for chrono is good for later
serde = { version = "1.0", features = ["derive"] } # "derive" feature for easy serialization
serde_json = "1.0"
